### ISSUE TITLE
在Headless模式下无法填写验证码

### ISSUE THREAD

**Issue by liups233** [Trojblue/TSDM-coin-farmer#1]
我用的是服务器Ubuntu（无图形界面），浏览器设置的Headless模式，输不了验证码
建议直接把验证码的链接显示出来

**Comment by liups233** [comment]
已解决，在Windows下先生成cookies.json，然后复制到服务器即可

**Comment by trojblue** [comment]
是的
而且验证码一般都是同一个链接每次请求刷新, 得先本地存下来再开个http server 有点麻烦就没弄
现在这样应该获取一次cookie可以用一个月
