### ISSUE TITLE
SCF 似乎没有正常登录

### ISSUE THREAD

**Issue by People-11** [Trojblue/TSDM-coin-farmer#10]
报错日志：
![Snipaste_2022-05-06_20-37-36](https://user-images.githubusercontent.com/41558215/167134293-1f716ac7-1f43-40e3-b3f2-4acceb7bb471.png)
cookies.json配置：
![Snipaste_2022-05-06_20-38-55](https://user-images.githubusercontent.com/41558215/167134394-3c6ee5d6-a29e-4922-bd5e-b19a93fdaf15.png)

**Comment by howdareyo** [comment]
https://github.com/trojblue/TSDM-coin-farmer/commit/ee52c159f5498a9e14d5d45a3022e9119cdc316b
那就直接老版本

**Comment by People-11** [comment]
谢谢您，但很抱歉，我可能已经不需要了，SCF不再有免费额度了

**Comment by howdareyo** [comment]
> 谢谢您，但很抱歉，我可能已经不需要了，SCF不再有免费额度了

话是这么说，但实际上是这样
![图片](https://user-images.githubusercontent.com/91058390/170814709-710baad5-b169-459d-bf5c-4791fb606f2b.png)
不过看个人了

**Comment by trojblue** [comment]
emm确实没想到SCF要没额度了, 从6月1号开始生效+三个月就是9月开始收费
之前有个fork带了github actions签到的功能, 现在一翻有找不到了 有空我改改吧
