### ISSUE TITLE
post签到出错

### ISSUE THREAD

**Issue by AsunaEmiria** [Trojblue/TSDM-coin-farmer#13]
**描述**:在服务器上，本地运行环境中出现签到错误，打工错误

**平台**:Centos8 Windows10

**产生方法**:

**相关代码/commit**:

**错误报告等**:=post打工出错: ('Connection aborted.', OSError(0, 'Error'))=====，=post签到出错: ('Connection aborted.', OSError(0, 'Error'))===

**Comment by trojblue** [comment]
可能是SSL错误, 检查下python/OpenSSL版本? 本地运行的话有ipv4地址吗

**Comment by AsunaEmiria** [comment]
有的，在本地运行有ipv4和ipv6，服务器上有ipv4，本地运行提示是一样的
