### ISSUE TITLE
请问这是什么原因

### ISSUE THREAD

**Issue by AsunaEmiria** [Trojblue/TSDM-coin-farmer#3]
Traceback (most recent call last):
  File "farmer.py", line 8, in <module>
    from dlc_stage1st import do_read_s1
  File "/docker/TSDM-coin-farmer/src/dlc_stage1st.py", line 10, in <module>
    from credentials import S1_CREDENTIALS
ImportError: cannot import name 'S1_CREDENTIALS'

**Comment by trojblue** [comment]
在src文件夹里新建`credentials.py`, 然后在里面添加变量`S1_CREDENTIALS = [["账户", "密码"]]`
这个变量是获取cookie的时候用的, 只挂机留个错的也行
当时写的时候没太考虑服务器运行的情况, 周末更新一下去掉这个依赖

**Comment by AsunaEmiria** [comment]
感谢回复，我等会试一下

**Comment by AsunaEmiria** [comment]
虽然能运行，但是并不会获取cookie
![Snipaste_2021-09-10_20-36-33](https://user-images.githubusercontent.com/49182516/132854281-3357d4bf-b972-41ee-b1b9-9f2ba034a257.png)
![Snipaste_2021-09-10_20-36-51](https://user-images.githubusercontent.com/49182516/132854284-12024f74-433a-4ac5-9103-8c15b50cfd32.png)

**Comment by trojblue** [comment]
先在windows上获取好cookie.json, 然后复制到vm同目录下
https://github.com/Trojblue/TSDM-coin-farmer/issues/1

关于cookie的逻辑正在改, 等周末写好再搞会方便一点

**Comment by AsunaEmiria** [comment]
好的，我到时候在用
