### ISSUE TITLE
vps报错了...

### ISSUE THREAD

**Issue by R31y** [Trojblue/TSDM-coin-farmer#6]
[root@VM-4-14-centos src]# python farmer.py -n
  File "farmer.py", line 11
SyntaxError: Non-ASCII character '\xe5' in file farmer.py on line 12, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by trojblue** [comment]
尝试加上`# -*- coding: UTF-8 -*-`, 不过你应该已经解决了吧
