### ISSUE TITLE
腾讯云报错

### ISSUE THREAD

**Issue by R31y** [Trojblue/TSDM-coin-farmer#7]
返回结果
{"errorCode":-1,"errorMessage":"Invoking task timed out after 3 seconds","requestId":"7a2ae0d9-63f6-46ea-8ca4-34cb7fe081fe","statusCode":433}

执行日志

START RequestId: 7a2ae0d9-63f6-46ea-8ca4-34cb7fe081fe

Event RequestId: 7a2ae0d9-63f6-46ea-8ca4-34cb7fe081fe

END RequestId: 7a2ae0d9-63f6-46ea-8ca4-34cb7fe081fe

Report RequestId: 7a2ae0d9-63f6-46ea-8ca4-34cb7fe081fe Duration:3000ms Memory:128MB MemUsage:16.7578MB

**Comment by trojblue** [comment]
光看这个log这看不出什么原因, 你看下程序目录里有没有自动保存的log或者txt文件?
还有腾讯云 函数管理 - "日志查询", 不知道还有没有当时的打印输出了

**Comment by R31y** [comment]
感谢回答，现在已经转vps了，脚本有运行成功

**Comment by howdareyo** [comment]
就当给后来者做一点微小的工作
这个东西应该是你腾讯云函数环境配置设置的执行超时时间3秒,因为默认就是3秒,所以执行时间超了可能会出现这个
随便调个20秒就行
