### ISSUE TITLE
重构没好？好多错误

### ISSUE THREAD

**Issue by moeshin** [Trojblue/TSDM-coin-farmer#9]
找不到变量、函数定义

**Comment by moeshin** [comment]
https://github.com/moeshin/TSDM-coin-farmer/commit/5c52e4bdc60e98649f6a490b8cc204252a8e9bd7

**Comment by moeshin** [comment]
cookie 是放到 `cookie_list`？

**Comment by trojblue** [comment]
emm换完结构以后还没在本地测试过，不好意思

> cookie 是放到 `cookie_list`？
放到src/privates/cookies.json, 可以复制doc/cookies.json.example来改

**Comment by moeshin** [comment]
cookie 我配置了，cookie  不是设置在请求头的 cookie_list 吧？https://github.com/moeshin/TSDM-coin-farmer/commit/02b60b95a9f82a9a850e19eaa07ed76d2dcfa0e6

**Comment by trojblue** [comment]
确实， 之前c6804b5 是cookie，重命名的时候被误改了
